// TBC Class Colors (official WoW class colors)
export const CLASS_COLORS: Record<string, string> = {
  warrior: "#C79C6E",
  paladin: "#F58CBA",
  hunter: "#ABD473",
  rogue: "#FFF569",
  priest: "#FFFFFF",
  shaman: "#0070DE",
  mage: "#69CCF0",
  warlock: "#9482C9",
  druid: "#FF7D0A",
}

export type WowClass =
  | "warrior"
  | "paladin"
  | "hunter"
  | "rogue"
  | "priest"
  | "shaman"
  | "mage"
  | "warlock"
  | "druid"

export type Spec = {
  id: string
  name: string
  class: WowClass
  role: "tank" | "healer" | "melee" | "ranged"
  buffs: string[]
  debuffs: string[]
}

export type Buff = {
  id: string
  name: string
  category: string
  description: string
  effect: string
  providedBy: string[]
}

export const SPECS: Spec[] = [
  // Warriors
  {
    id: "prot-warrior",
    name: "Protection",
    class: "warrior",
    role: "tank",
    buffs: ["battle-shout", "commanding-shout"],
    debuffs: ["sunder-armor", "thunder-clap", "demo-shout"],
  },
  {
    id: "arms-warrior",
    name: "Arms",
    class: "warrior",
    role: "melee",
    buffs: ["battle-shout"],
    debuffs: ["sunder-armor", "mortal-strike", "thunder-clap", "demo-shout"],
  },
  {
    id: "fury-warrior",
    name: "Fury",
    class: "warrior",
    role: "melee",
    buffs: ["battle-shout", "commanding-shout"],
    debuffs: ["sunder-armor", "demo-shout"],
  },
  // Paladins
  {
    id: "prot-paladin",
    name: "Protection",
    class: "paladin",
    role: "tank",
    buffs: [
      "blessing-kings",
      "blessing-might",
      "blessing-wisdom",
      "blessing-salvation",
      "devotion-aura",
      "retribution-aura",
      "sanctity-aura",
    ],
    debuffs: ["judgement-crusader"],
  },
  {
    id: "holy-paladin",
    name: "Holy",
    class: "paladin",
    role: "healer",
    buffs: [
      "blessing-kings",
      "blessing-might",
      "blessing-wisdom",
      "blessing-salvation",
      "devotion-aura",
      "concentration-aura",
      "blessing-light",
    ],
    debuffs: ["judgement-crusader"],
  },
  {
    id: "ret-paladin",
    name: "Retribution",
    class: "paladin",
    role: "melee",
    buffs: [
      "blessing-kings",
      "blessing-might",
      "blessing-wisdom",
      "blessing-salvation",
      "sanctity-aura",
      "crusader-strike",
    ],
    debuffs: ["judgement-crusader", "judgement-wisdom"],
  },
  // Hunters
  {
    id: "bm-hunter",
    name: "Beast Mastery",
    class: "hunter",
    role: "ranged",
    buffs: ["trueshot-aura", "ferocious-inspiration"],
    debuffs: ["hunters-mark", "expose-weakness"],
  },
  {
    id: "mm-hunter",
    name: "Marksmanship",
    class: "hunter",
    role: "ranged",
    buffs: ["trueshot-aura"],
    debuffs: ["hunters-mark", "expose-weakness"],
  },
  {
    id: "sv-hunter",
    name: "Survival",
    class: "hunter",
    role: "ranged",
    buffs: ["trueshot-aura"],
    debuffs: ["hunters-mark", "expose-weakness"],
  },
  // Rogues
  {
    id: "combat-rogue",
    name: "Combat",
    class: "rogue",
    role: "melee",
    buffs: [],
    debuffs: ["expose-armor", "wound-poison"],
  },
  {
    id: "assassination-rogue",
    name: "Assassination",
    class: "rogue",
    role: "melee",
    buffs: [],
    debuffs: ["expose-armor", "wound-poison", "deadly-poison"],
  },
  {
    id: "subtlety-rogue",
    name: "Subtlety",
    class: "rogue",
    role: "melee",
    buffs: [],
    debuffs: ["expose-armor", "wound-poison"],
  },
  // Priests
  {
    id: "disc-priest",
    name: "Discipline",
    class: "priest",
    role: "healer",
    buffs: ["power-word-fortitude", "divine-spirit", "shadow-protection"],
    debuffs: [],
  },
  {
    id: "holy-priest",
    name: "Holy",
    class: "priest",
    role: "healer",
    buffs: [
      "power-word-fortitude",
      "divine-spirit",
      "shadow-protection",
      "inspiration",
    ],
    debuffs: [],
  },
  {
    id: "shadow-priest",
    name: "Shadow",
    class: "priest",
    role: "ranged",
    buffs: ["power-word-fortitude", "divine-spirit", "shadow-protection"],
    debuffs: ["shadow-weaving", "misery"],
  },
  // Shamans
  {
    id: "resto-shaman",
    name: "Restoration",
    class: "shaman",
    role: "healer",
    buffs: [
      "mana-spring-totem",
      "healing-stream-totem",
      "wrath-of-air-totem",
      "earth-shield",
    ],
    debuffs: [],
  },
  {
    id: "elemental-shaman",
    name: "Elemental",
    class: "shaman",
    role: "ranged",
    buffs: [
      "totem-of-wrath",
      "wrath-of-air-totem",
      "mana-spring-totem",
    ],
    debuffs: [],
  },
  {
    id: "enhance-shaman",
    name: "Enhancement",
    class: "shaman",
    role: "melee",
    buffs: [
      "windfury-totem",
      "grace-of-air-totem",
      "strength-of-earth-totem",
      "unleashed-rage",
    ],
    debuffs: [],
  },
  // Mages
  {
    id: "arcane-mage",
    name: "Arcane",
    class: "mage",
    role: "ranged",
    buffs: ["arcane-intellect", "arcane-brilliance"],
    debuffs: [],
  },
  {
    id: "fire-mage",
    name: "Fire",
    class: "mage",
    role: "ranged",
    buffs: ["arcane-intellect", "arcane-brilliance"],
    debuffs: ["improved-scorch"],
  },
  {
    id: "frost-mage",
    name: "Frost",
    class: "mage",
    role: "ranged",
    buffs: ["arcane-intellect", "arcane-brilliance"],
    debuffs: ["winters-chill"],
  },
  // Warlocks
  {
    id: "affliction-warlock",
    name: "Affliction",
    class: "warlock",
    role: "ranged",
    buffs: ["blood-pact", "fel-intelligence"],
    debuffs: ["curse-elements", "curse-shadows", "curse-recklessness", "shadow-embrace"],
  },
  {
    id: "demonology-warlock",
    name: "Demonology",
    class: "warlock",
    role: "ranged",
    buffs: ["blood-pact", "fel-intelligence", "demonic-pact"],
    debuffs: ["curse-elements", "curse-shadows", "curse-recklessness"],
  },
  {
    id: "destruction-warlock",
    name: "Destruction",
    class: "warlock",
    role: "ranged",
    buffs: ["blood-pact", "fel-intelligence"],
    debuffs: ["curse-elements", "curse-shadows", "curse-recklessness", "shadow-and-flame"],
  },
  // Druids
  {
    id: "resto-druid",
    name: "Restoration",
    class: "druid",
    role: "healer",
    buffs: ["mark-of-the-wild", "gift-of-the-wild", "tree-of-life"],
    debuffs: [],
  },
  {
    id: "balance-druid",
    name: "Balance",
    class: "druid",
    role: "ranged",
    buffs: ["mark-of-the-wild", "gift-of-the-wild", "moonkin-aura"],
    debuffs: ["faerie-fire", "insect-swarm"],
  },
  {
    id: "feral-druid",
    name: "Feral (Cat)",
    class: "druid",
    role: "melee",
    buffs: ["mark-of-the-wild", "gift-of-the-wild", "leader-of-the-pack"],
    debuffs: ["faerie-fire", "mangle"],
  },
  {
    id: "bear-druid",
    name: "Feral (Bear)",
    class: "druid",
    role: "tank",
    buffs: ["mark-of-the-wild", "gift-of-the-wild", "leader-of-the-pack"],
    debuffs: ["faerie-fire", "mangle", "demo-roar"],
  },
]

export const BUFFS: Buff[] = [
  // Warrior Buffs
  {
    id: "battle-shout",
    name: "Battle Shout",
    category: "Attack Power",
    description: "+305 Attack Power to party",
    effect: "The warrior lets out a battle shout, increasing the Attack Power of all party members within 20 yards by 305 for 2 minutes. Essential for melee groups.",
    providedBy: ["prot-warrior", "arms-warrior", "fury-warrior"],
  },
  {
    id: "commanding-shout",
    name: "Commanding Shout",
    category: "Stamina",
    description: "+1080 Health to party",
    effect: "Increases the Stamina of all party members within 20 yards by 1080 for 2 minutes. Useful for survivability during heavy damage phases.",
    providedBy: ["prot-warrior", "fury-warrior"],
  },
  // Paladin Buffs
  {
    id: "blessing-kings",
    name: "Blessing of Kings",
    category: "Stats",
    description: "+10% to all stats",
    effect: "Places a blessing on the target, increasing total stats (Strength, Agility, Stamina, Intellect, Spirit) by 10%. The most powerful single-target stat buff in TBC.",
    providedBy: ["prot-paladin", "holy-paladin", "ret-paladin"],
  },
  {
    id: "blessing-might",
    name: "Blessing of Might",
    category: "Attack Power",
    description: "+220 Attack Power",
    effect: "Places a blessing on the target, increasing Attack Power by 220 for 10 minutes. Preferred by physical DPS who don't need mana.",
    providedBy: ["prot-paladin", "holy-paladin", "ret-paladin"],
  },
  {
    id: "blessing-wisdom",
    name: "Blessing of Wisdom",
    category: "Mana",
    description: "+41 MP5",
    effect: "Places a blessing on the target, restoring 41 mana every 5 seconds for 10 minutes. Essential for healers and mana-hungry casters.",
    providedBy: ["prot-paladin", "holy-paladin", "ret-paladin"],
  },
  {
    id: "blessing-salvation",
    name: "Blessing of Salvation",
    category: "Threat",
    description: "-30% threat generated",
    effect: "Places a blessing on the target, reducing threat generated by 30% for 10 minutes. Critical for high-DPS players to avoid pulling aggro.",
    providedBy: ["prot-paladin", "holy-paladin", "ret-paladin"],
  },
  {
    id: "blessing-light",
    name: "Blessing of Light",
    category: "Healing",
    description: "Increased healing received",
    effect: "Places a blessing on the target that increases the effects of Holy Light by up to 580 and Flash of Light by up to 185. Best on tanks.",
    providedBy: ["holy-paladin"],
  },
  {
    id: "devotion-aura",
    name: "Devotion Aura",
    category: "Armor",
    description: "+861 Armor to party",
    effect: "Gives 861 additional armor to party members within 30 yards. Reduces physical damage taken, especially useful for melee groups.",
    providedBy: ["prot-paladin"],
  },
  {
    id: "retribution-aura",
    name: "Retribution Aura",
    category: "Damage",
    description: "Holy damage to attackers",
    effect: "Causes 26 Holy damage to any enemy that strikes a party member within 30 yards. Provides passive threat for tanks.",
    providedBy: ["prot-paladin"],
  },
  {
    id: "sanctity-aura",
    name: "Sanctity Aura",
    category: "Damage",
    description: "+10% Holy damage to party",
    effect: "Increases Holy damage done by party members within 30 yards by 10%. Powerful for Retribution Paladins and Holy damage abilities.",
    providedBy: ["prot-paladin", "ret-paladin"],
  },
  {
    id: "concentration-aura",
    name: "Concentration Aura",
    category: "Utility",
    description: "Reduce spell pushback",
    effect: "All party members within 30 yards lose 35% less casting or channeling time when damaged. Essential for healer groups during heavy raid damage.",
    providedBy: ["holy-paladin"],
  },
  {
    id: "crusader-strike",
    name: "Crusader Strike",
    category: "Damage",
    description: "Refreshes judgements",
    effect: "An instant strike that causes 110% weapon damage and refreshes all Judgements on the target. Core Retribution ability for sustained damage.",
    providedBy: ["ret-paladin"],
  },
  // Hunter Buffs
  {
    id: "trueshot-aura",
    name: "Trueshot Aura",
    category: "Attack Power",
    description: "+125 AP to party",
    effect: "Increases the Attack Power of party members within 45 yards by 125. Stacks with other AP buffs, making hunters valuable for physical DPS groups.",
    providedBy: ["bm-hunter", "mm-hunter", "sv-hunter"],
  },
  {
    id: "ferocious-inspiration",
    name: "Ferocious Inspiration",
    category: "Damage",
    description: "+3% damage to party",
    effect: "When your pet scores a critical hit, all party members gain 3% increased damage for 10 seconds. One of the strongest raid DPS buffs in TBC.",
    providedBy: ["bm-hunter"],
  },
  // Priest Buffs
  {
    id: "power-word-fortitude",
    name: "Power Word: Fortitude",
    category: "Stamina",
    description: "+79 Stamina",
    effect: "Power infuses the target, increasing their Stamina by 79 for 1 hour. One of the most essential raid buffs for survivability.",
    providedBy: ["disc-priest", "holy-priest", "shadow-priest"],
  },
  {
    id: "divine-spirit",
    name: "Divine Spirit",
    category: "Spirit",
    description: "+50 Spirit",
    effect: "Holy power infuses the target, increasing their Spirit by 50 for 1 hour. Improves mana regeneration and pairs well with Blessing of Kings.",
    providedBy: ["disc-priest", "holy-priest", "shadow-priest"],
  },
  {
    id: "shadow-protection",
    name: "Shadow Protection",
    category: "Resistance",
    description: "+70 Shadow Resistance",
    effect: "Power infuses the target, increasing Shadow Resistance by 70 for 10 minutes. Critical for fights with heavy Shadow damage.",
    providedBy: ["disc-priest", "holy-priest", "shadow-priest"],
  },
  {
    id: "inspiration",
    name: "Inspiration",
    category: "Mitigation",
    description: "-25% physical damage taken",
    effect: "Reduces physical damage taken by 25% for 15 seconds after receiving a critical heal. Essential for tank survival during heavy damage.",
    providedBy: ["holy-priest"],
  },
  // Shaman Buffs
  {
    id: "mana-spring-totem",
    name: "Mana Spring Totem",
    category: "Mana",
    description: "+25 MP5 to party",
    effect: "Summons a Mana Spring Totem with 5 health at the feet of the caster that restores 25 mana every 2 seconds to party members within 20 yards.",
    providedBy: ["resto-shaman", "elemental-shaman"],
  },
  {
    id: "healing-stream-totem",
    name: "Healing Stream Totem",
    category: "Healing",
    description: "Heals party over time",
    effect: "Summons a Healing Stream Totem that heals party members within 20 yards for 25 every 2 seconds. Provides passive healing during fights.",
    providedBy: ["resto-shaman"],
  },
  {
    id: "wrath-of-air-totem",
    name: "Wrath of Air Totem",
    category: "Spell Power",
    description: "+101 Spell Power to party",
    effect: "Summons a Wrath of Air Totem that increases the spell damage and healing of party members within 20 yards by 101. Essential for caster groups.",
    providedBy: ["resto-shaman", "elemental-shaman"],
  },
  {
    id: "totem-of-wrath",
    name: "Totem of Wrath",
    category: "Spell Power",
    description: "+3% Spell Hit/Crit to party",
    effect: "Summons a Totem of Wrath with 5 health at the feet of the caster. The totem increases spell crit chance by 3% and spell hit chance by 3% for all party members within 20 yards.",
    providedBy: ["elemental-shaman"],
  },
  {
    id: "windfury-totem",
    name: "Windfury Totem",
    category: "Melee",
    description: "Extra attacks to party",
    effect: "Summons a Windfury Totem that grants party members within 20 yards a 20% chance to gain 1 extra attack with 445 bonus Attack Power. The most powerful melee buff in TBC.",
    providedBy: ["enhance-shaman"],
  },
  {
    id: "grace-of-air-totem",
    name: "Grace of Air Totem",
    category: "Agility",
    description: "+77 Agility to party",
    effect: "Summons a Grace of Air Totem that increases the Agility of party members within 20 yards by 77. Excellent for rogues, hunters, and feral druids.",
    providedBy: ["enhance-shaman"],
  },
  {
    id: "strength-of-earth-totem",
    name: "Strength of Earth Totem",
    category: "Strength",
    description: "+86 Strength to party",
    effect: "Summons a Strength of Earth Totem that increases the Strength of party members within 20 yards by 86. Great for warriors and Enhancement shamans.",
    providedBy: ["enhance-shaman"],
  },
  {
    id: "unleashed-rage",
    name: "Unleashed Rage",
    category: "Attack Power",
    description: "+10% AP to party",
    effect: "Causes your critical hits with melee attacks to increase all party members' attack power by 10% for 10 seconds. One of the strongest melee buffs.",
    providedBy: ["enhance-shaman"],
  },
  {
    id: "earth-shield",
    name: "Earth Shield",
    category: "Healing",
    description: "Heals target on hit",
    effect: "Protects the target with an earthen shield, causing attacks to heal the target for 270 and giving a 30% chance to avoid spell interruption. Lasts 10 minutes or 6 charges.",
    providedBy: ["resto-shaman"],
  },
  // Mage Buffs
  {
    id: "arcane-intellect",
    name: "Arcane Intellect",
    category: "Intellect",
    description: "+40 Intellect",
    effect: "Increases the target's Intellect by 40 for 1 hour. Increases mana pool and spell critical strike chance.",
    providedBy: ["arcane-mage", "fire-mage", "frost-mage"],
  },
  {
    id: "arcane-brilliance",
    name: "Arcane Brilliance",
    category: "Intellect",
    description: "+40 Intellect (raid-wide)",
    effect: "Infuses the target's party with brilliance, increasing their Intellect by 40 for 1 hour. The raid-wide version of Arcane Intellect.",
    providedBy: ["arcane-mage", "fire-mage", "frost-mage"],
  },
  // Warlock Buffs
  {
    id: "blood-pact",
    name: "Blood Pact",
    category: "Stamina",
    description: "+66 Stamina to party",
    effect: "Increases the Stamina of all party members by 66. Provided by the Imp pet. Stacks with Power Word: Fortitude.",
    providedBy: ["affliction-warlock", "demonology-warlock", "destruction-warlock"],
  },
  {
    id: "fel-intelligence",
    name: "Fel Intelligence",
    category: "Intellect",
    description: "+48 Intellect/Spirit to party",
    effect: "Increases the Intellect and Spirit of all party members by 48. Provided by the Felhunter pet. Great for caster groups.",
    providedBy: ["affliction-warlock", "demonology-warlock", "destruction-warlock"],
  },
  {
    id: "demonic-pact",
    name: "Demonic Pact",
    category: "Spell Power",
    description: "+10% Spell Power to party",
    effect: "When your demon critically hits, you and your party gain 10% of your spell power as additional spell power for 12 seconds. Powerful caster buff.",
    providedBy: ["demonology-warlock"],
  },
  // Druid Buffs
  {
    id: "mark-of-the-wild",
    name: "Mark of the Wild",
    category: "Stats",
    description: "+14 to all stats, +340 Armor, +25 All Resistances",
    effect: "Increases the target's armor by 340, all attributes by 14, and all resistances by 25 for 1 hour. One of the most comprehensive buffs in the game.",
    providedBy: ["resto-druid", "balance-druid", "feral-druid", "bear-druid"],
  },
  {
    id: "gift-of-the-wild",
    name: "Gift of the Wild",
    category: "Stats",
    description: "Mark of the Wild (raid-wide)",
    effect: "Gives the Gift of the Wild to all party and raid members, increasing armor by 340, all attributes by 14, and all resistances by 25 for 1 hour.",
    providedBy: ["resto-druid", "balance-druid", "feral-druid", "bear-druid"],
  },
  {
    id: "tree-of-life",
    name: "Tree of Life Aura",
    category: "Healing",
    description: "+25% healing from HoTs to party",
    effect: "While in Tree of Life form, increases healing received by 25% of the druid's spirit for all party members within 45 yards. Also reduces mana cost of HoTs by 20%.",
    providedBy: ["resto-druid"],
  },
  {
    id: "moonkin-aura",
    name: "Moonkin Aura",
    category: "Spell Crit",
    description: "+5% Spell Crit to party",
    effect: "While in Moonkin form, increases the spell critical chance of all party members within 30 yards by 5%. Essential buff for caster groups.",
    providedBy: ["balance-druid"],
  },
  {
    id: "leader-of-the-pack",
    name: "Leader of the Pack",
    category: "Crit",
    description: "+5% Melee/Ranged Crit to party",
    effect: "While in Cat, Bear, or Dire Bear form, the leader of the pack increases melee and ranged critical chance of all party members within 45 yards by 5%.",
    providedBy: ["feral-druid", "bear-druid"],
  },
]

export const DEBUFFS: Buff[] = [
  // Warrior Debuffs
  {
    id: "sunder-armor",
    name: "Sunder Armor",
    category: "Armor Reduction",
    description: "-2600 Armor (5 stacks)",
    effect: "Sunders the target's armor, reducing it by 520 per stack. Can be applied up to 5 times for a total of -2600 armor. Essential for maximizing physical DPS.",
    providedBy: ["prot-warrior", "arms-warrior", "fury-warrior"],
  },
  {
    id: "thunder-clap",
    name: "Thunder Clap",
    category: "Attack Speed",
    description: "-10% Attack Speed",
    effect: "Blasts nearby enemies, increasing the time between their attacks by 10% for 30 seconds. Reduces incoming physical damage significantly on boss fights.",
    providedBy: ["prot-warrior", "arms-warrior"],
  },
  {
    id: "demo-shout",
    name: "Demoralizing Shout",
    category: "Attack Power",
    description: "-300 Attack Power",
    effect: "Demoralizes nearby enemies, reducing their melee attack power by 300 for 30 seconds. Stacks with Demoralizing Roar for maximum mitigation.",
    providedBy: ["prot-warrior", "arms-warrior", "fury-warrior"],
  },
  {
    id: "mortal-strike",
    name: "Mortal Strike",
    category: "Healing Reduction",
    description: "-50% healing received",
    effect: "A vicious strike that deals weapon damage plus 210 and wounds the target, reducing the effectiveness of healing spells by 50% for 10 seconds.",
    providedBy: ["arms-warrior"],
  },
  // Paladin Debuffs
  {
    id: "judgement-crusader",
    name: "Judgement of the Crusader",
    category: "Holy Damage",
    description: "+219 Holy damage taken",
    effect: "Fills the target with the spirit of the Crusader for 20 seconds, increasing Holy damage taken by up to 219. Significantly boosts Paladin damage.",
    providedBy: ["prot-paladin", "holy-paladin", "ret-paladin"],
  },
  {
    id: "judgement-wisdom",
    name: "Judgement of Wisdom",
    category: "Mana",
    description: "Attacks restore mana",
    effect: "Judges the target, causing attacks against it to restore mana to the attacker. Excellent for sustaining mana on long fights.",
    providedBy: ["ret-paladin"],
  },
  // Hunter Debuffs
  {
    id: "hunters-mark",
    name: "Hunter's Mark",
    category: "Attack Power",
    description: "+110 Ranged AP vs target",
    effect: "Places the Hunter's Mark on the target, increasing the ranged attack power of all attackers by 110 against that target. Lasts until cancelled.",
    providedBy: ["bm-hunter", "mm-hunter", "sv-hunter"],
  },
  {
    id: "expose-weakness",
    name: "Expose Weakness",
    category: "Attack Power",
    description: "+AP based on Agility",
    effect: "Your ranged crits have a 100% chance to apply Expose Weakness, increasing attack power against that target by 25% of your Agility for 7 seconds.",
    providedBy: ["bm-hunter", "mm-hunter", "sv-hunter"],
  },
  // Rogue Debuffs
  {
    id: "expose-armor",
    name: "Expose Armor",
    category: "Armor Reduction",
    description: "-2050 Armor",
    effect: "Finishing move that exposes the target's armor, reducing it by 2050 at 5 combo points for 30 seconds. Does not stack with Sunder Armor.",
    providedBy: ["combat-rogue", "assassination-rogue", "subtlety-rogue"],
  },
  {
    id: "wound-poison",
    name: "Wound Poison",
    category: "Healing Reduction",
    description: "-10% healing received",
    effect: "Coats a weapon with poison that lasts for 1 hour. Each strike has a 30% chance to poison the enemy, reducing all healing effects by 10% for 15 seconds.",
    providedBy: ["combat-rogue", "assassination-rogue", "subtlety-rogue"],
  },
  {
    id: "deadly-poison",
    name: "Deadly Poison",
    category: "Damage",
    description: "Nature DoT",
    effect: "Coats a weapon with poison that lasts for 1 hour. Each strike has a 30% chance to poison the enemy for 180 Nature damage over 12 seconds. Stacks up to 5 times.",
    providedBy: ["assassination-rogue"],
  },
  // Priest Debuffs
  {
    id: "shadow-weaving",
    name: "Shadow Weaving",
    category: "Shadow Damage",
    description: "+10% Shadow damage taken",
    effect: "Your Shadow damage spells have a 100% chance to increase Shadow damage taken by 2% per stack, up to 10% at 5 stacks. Essential for Shadow and Warlock damage.",
    providedBy: ["shadow-priest"],
  },
  {
    id: "misery",
    name: "Misery",
    category: "Spell Hit",
    description: "+5% Spell Hit vs target",
    effect: "Your Shadow Word: Pain, Mind Flay, and Vampiric Touch cause the target to take 5% more spell damage. Allows casters to reduce hit rating on gear.",
    providedBy: ["shadow-priest"],
  },
  // Mage Debuffs
  {
    id: "improved-scorch",
    name: "Improved Scorch",
    category: "Fire Damage",
    description: "+15% Fire damage taken",
    effect: "Your Scorch has a 100% chance to cause your target to be vulnerable to Fire damage, increasing Fire damage taken by 3% per stack, up to 15% at 5 stacks.",
    providedBy: ["fire-mage"],
  },
  {
    id: "winters-chill",
    name: "Winter's Chill",
    category: "Frost Crit",
    description: "+10% Frost Crit chance",
    effect: "Gives your Frost damage spells a 100% chance to apply Winter's Chill, increasing Frost spell critical strike chance against the target by 2% per stack, up to 10%.",
    providedBy: ["frost-mage"],
  },
  // Warlock Debuffs
  {
    id: "curse-elements",
    name: "Curse of the Elements",
    category: "Magic Damage",
    description: "+10% Arcane/Fire/Frost damage",
    effect: "Curses the target, increasing Arcane, Fire, and Frost damage taken by 10% and reducing resistances by 88 for 5 minutes. One of the strongest raid debuffs.",
    providedBy: ["affliction-warlock", "demonology-warlock", "destruction-warlock"],
  },
  {
    id: "curse-shadows",
    name: "Curse of Shadow",
    category: "Magic Damage",
    description: "+10% Shadow/Arcane damage",
    effect: "Curses the target, increasing Shadow and Arcane damage taken by 10% and reducing Shadow and Arcane resistances by 88 for 5 minutes.",
    providedBy: ["affliction-warlock", "demonology-warlock", "destruction-warlock"],
  },
  {
    id: "curse-recklessness",
    name: "Curse of Recklessness",
    category: "Armor Reduction",
    description: "-800 Armor",
    effect: "Curses the target, reducing armor by 800 but increasing melee attack power by 135 for 2 minutes. The armor reduction benefits all physical DPS.",
    providedBy: ["affliction-warlock", "demonology-warlock", "destruction-warlock"],
  },
  {
    id: "shadow-embrace",
    name: "Shadow Embrace",
    category: "Physical Damage",
    description: "-5% Physical damage dealt",
    effect: "Your Corruption, Curse of Agony, and Seed of Corruption have a chance to cause Shadow Embrace, reducing physical damage done by 5% for 12 seconds.",
    providedBy: ["affliction-warlock"],
  },
  {
    id: "shadow-and-flame",
    name: "Shadow and Flame",
    category: "Shadow/Fire Damage",
    description: "+5% Shadow/Fire damage",
    effect: "Your Shadow Bolt and Incinerate have a chance to increase Fire and Shadow damage by 5% for 10 seconds. Boosts both Warlock and Mage damage.",
    providedBy: ["destruction-warlock"],
  },
  // Druid Debuffs
  {
    id: "faerie-fire",
    name: "Faerie Fire",
    category: "Armor Reduction",
    description: "-610 Armor",
    effect: "Decreases the armor of the target by 610 for 40 seconds and prevents stealth or invisibility. Feral version can be applied in Cat or Bear form.",
    providedBy: ["balance-druid", "feral-druid", "bear-druid"],
  },
  {
    id: "insect-swarm",
    name: "Insect Swarm",
    category: "Miss Chance",
    description: "+2% Miss chance",
    effect: "The enemy target is swarmed by insects, decreasing their chance to hit by 2% and causing Nature damage over 12 seconds. Great for tank mitigation.",
    providedBy: ["balance-druid"],
  },
  {
    id: "mangle",
    name: "Mangle",
    category: "Bleed Damage",
    description: "+30% Bleed damage",
    effect: "Mangle the target, inflicting damage and causing the target to take 30% additional damage from bleed effects for 12 seconds. Essential for Feral and Rogue damage.",
    providedBy: ["feral-druid", "bear-druid"],
  },
  {
    id: "demo-roar",
    name: "Demoralizing Roar",
    category: "Attack Power",
    description: "-248 Attack Power",
    effect: "The druid roars, decreasing nearby enemies' melee attack power by 248 for 30 seconds. Stacks with Demoralizing Shout for maximum effect.",
    providedBy: ["bear-druid"],
  },
]

export const BUFF_CATEGORIES = [
  "Stats",
  "Attack Power",
  "Spell Power",
  "Stamina",
  "Intellect",
  "Spirit",
  "Agility",
  "Strength",
  "Mana",
  "Healing",
  "Crit",
  "Spell Crit",
  "Melee",
  "Damage",
  "Armor",
  "Resistance",
  "Mitigation",
  "Threat",
  "Utility",
]

export const DEBUFF_CATEGORIES = [
  "Armor Reduction",
  "Attack Power",
  "Attack Speed",
  "Healing Reduction",
  "Holy Damage",
  "Shadow Damage",
  "Fire Damage",
  "Magic Damage",
  "Spell Hit",
  "Frost Crit",
  "Physical Damage",
  "Shadow/Fire Damage",
  "Miss Chance",
  "Bleed Damage",
  "Damage",
  "Mana",
]
